
name: CICD-qa

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: qa
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write

    defaults:
      run:
        shell: bash

    steps:      
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Script
        working-directory: './'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |-
          echo ${{ vars.VARIABLE }}
          
          