name: CICD-dev

on:
  push:
    branches: [ "dev" ]
    paths:
      - '/**'
      - '.github/workflows/CICD-dev.yml'

  workflow_dispatch:

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write

    defaults:
      run:
        shell: bash

    steps:      
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Script
        working-directory: './'
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: |-
          echo ${{ env.VARIABLE }}
          
          